name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: make COVERAGE_TEST=1
    - name: check
      run: make check
    - name: gcov
      run: make gcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
