name: Coverage Testing on public beta of Ubuntu 24.04

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  coverage-test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npm install -g bats
    - run: bats -v      
    - name: configure
      run: ./configure --enable-code-coverage
    - name: build
      run: make -j
    - name: check
      run: make check
    - name: gcov
      run: make gcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
