name: Coverage Testing

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  coverage-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: build
      run: make COVERAGE_TEST=1
    - name: check
      run: make check
    - name: gcov
      run: make gcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
