name: Unit Testing

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  unit-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install GNU Getopt on macOS
      if ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install gnu-getopt
    - name: configure
      run: ./configure
    - name: build
      run: make
    - name: check
      run: make check
